CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
ORYX_ENABLE = yes
RGB_MATRIX_CUSTOM_KB = yes
SPACE_CADET_ENABLE = no
CAPS_WORD_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = yes
DEFERRED_EXEC_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
AUDIO_ENABLE = yes
LEADER_ENABLE = yes
UNICODE_COMMON = yes
# TAP_DANCE_ENABLE = yes

SRC += inactivity.c
SRC += launch_tetris.c
SRC += led_indicators.c
SRC += music.c
SRC += one_handed.c
SRC += tap_hold.c
SRC += tetris.c
SRC += unicode_leader.c