#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "myZD3/RjmRb4"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

#define RGB_MATRIX_DEFAULT_ON true
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CUSTOM_INVERSE_MULTISPLASH
// #define RGB_MATRIX_MAXIMUM_BRIGHTNESS 255
#define RGB_MATRIX_DEFAULT_HUE 135
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_VAL 255
#define RGB_MATRIX_HUE_STEP 5
#define RGB_MATRIX_SAT_STEP 20
#define RGB_MATRIX_DEFAULT_SPD 70

#define INACTIVITY_TIMEOUT 300000
// #define INACTIVITY_TIMEOUT 10000
#define RGB_MATRIX_FADE_OUT_DURATION_MS 5000

#define MOONLANDER_USER_LEDS

#undef  TEMPO_DEFAULT
#define TEMPO_DEFAULT 80

#define STARTUP_SONG SONG(ZELDA_PUZZLE)