CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
ORYX_ENABLE = yes
RGB_MATRIX_CUSTOM_KB = yes
SPACE_CADET_ENABLE = no
CAPS_WORD_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = yes
DEFERRED_EXEC_ENABLE = yes

AUDIO_ENABLE = yes
SRC += tetris.c
SRC += music.c